### ISSUE TITLE
compiler bug, can you help me?

### ISSUE THREAD

**Issue by xuxilei** [IBMSparkGPU/GPUEnabler#32]
[root@localhost GPUEnabler-master]# ./bin/run-example SparkPi

Executing : mvn -q scala:run -DmainClass=com.ibm.gpuenabler.SparkPi -DaddArgs="local[*]"

[ERROR] Failed to execute goal org.scala-tools:maven-scala-plugin:2.15.2:run (default-cli) on project gpu-enabler-examples_2.11: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240(Exit value: 240) -> [Help 1]

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by kavanabhat** [comment]
SparkPi class is not part of the GPUEnabler package. So, ClassNotFoundException is being thrown.
