### ISSUE TITLE
Logistic regression algorithm in SparkGPULR.scala

### ISSUE THREAD

**Issue by yiskylee** [IBMSparkGPU/GPUEnabler#45]
The function used in SparkGPULR for calculating the gradient is:
`dmulvs(p.x, (1 / (1 + exp(-p.y * (ddotvv(wbc.value, p.x)))) - 1) * p.y)`, 
and the mathematical formula of it is:
![gradient_gpuenabler](https://cloud.githubusercontent.com/assets/2600667/25195827/cc03b934-250c-11e7-8c9c-a7c80e499fbd.PNG)

But I think the formula should be this:
![gradient](https://cloud.githubusercontent.com/assets/2600667/25195851/dfc82018-250c-11e7-923b-6bff7c3f4c74.PNG)

But this formula is for when y is binary while the y in the SparkGPULR is either -1 or 1. Could you provide an algorithm reference to your implementation?

Thanks.

**Comment by josiahsams** [comment]
The formula we used is applicable only if the output labels are -1 and 1. For regular LR with binary labels, the formula you mentioned is correct.

**Comment by josiahsams** [comment]
Soon we will add an example for the regular LR problem(binary label).
