### ISSUE TITLE
GPUEnabler not found by sbt and maven

### ISSUE THREAD

**Issue by asdfghjBennyHuang** [IBMSparkGPU/GPUEnabler#84]
When I add the dependency in builb.sbt and try to package it, the error shows that:
sbt.librarymanagement.ResolveException: unresolved dependency: com.ibm#gpu-enabler_2.11;2.0.0: not found

Then I change to maven, however, it's still gives error as following: 
WARNING: The POM for com.ibm:gpu-enabler_2.11:jar:2.0.0 is missing, no dependency information available 

It seems that the GPUEnabler is not available in the repository anymore?

I am using ubuntu 17.04, CUDA and Spark are both installed.

**Comment by josiahsams** [comment]
`gpu-enabler` is not available in public maven repository yet. So you have to build this project and install it to your local maven repository to start including it in your projects.  
Follow this step: https://github.com/IBMSparkGPU/GPUEnabler#building-from-source

**Comment by asdfghjBennyHuang** [comment]
Thanks so much, I've successfully build the binary file. Is there any chance in the future we can see this in public repository?
